### ISSUE TITLE
return

### ISSUE THREAD

**Issue by caliendojulien** [agnes-guillet21/coursPHP#1]
https://github.com/agnes-guillet21/coursPHP/blob/414151f8320fc2d94e2e32efcb83c665bf5d7462/module%203%20POO/tp1Classes/VilleConstructeur.class.php#L82

A quoi sert le "return" ici ?

**Comment by agnes-guillet21** [comment]
à retourner le nom le plus long entre les 2 noms comparés,
c'est inutile ?

**Comment by caliendojulien** [comment]
Je crois comprendre, en lisant ton code, que tu utilise la méthode comparaison comme une procédure (a la ligne 19).
Ce n'est pas une grosse erreur. C'était surtout une excuse pour te montrer comment fonctionne les "issues" sur GitHub.

Je te montre demain comment la clôturer avec un commit.

**Comment by agnes-guillet21** [comment]
je sais le différence entre une procédure et une fonction ( si si je t'assure) mais je pensais  utiliser ma méthode comme une fonction L19 XD
petite ou grosse  ca reste une erreur ...^^ 
 je vais essayer de trouver des exos supp sur les fonctions en php, histoire d'avoir plus automatisme.
